### ISSUE TITLE
Problem in the student version

### ISSUE THREAD

**Issue by PaBu04** [kit-sdq/eclipse-artemis#318]
### Description

When I open Eclipse Artemis, I always get the following error, as you can see, even on different devices.
Everything was working fine until last week.
![error](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/assets/88597864/76104a4b-190d-48ee-bb49-cce695c0c0d4)

**Comment by Shirkanesi** [comment]
Hi,
I'm sorry you are having issues with this project. However, support for the student feature has been dropped in [v4.0.0](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/releases/tag/v4.0.0) as it was'nt really used at all.

So sadly your issue will most likely be a won't-fix. Sorry.


FYI @dfuchss

**Comment by dfuchss** [comment]
Hi @PaBu04 ,
unfortunately, we have dropped the support for the student edition of Eclipse Artemis since most students are directly using git in their IDEs (as @Shirkanesi said)

If a huge amount of students want this feature back, we might provide the feature in the future. (So feel free to react with :+1: if the feature would be useful for you)

For now, we will close this PR as we currently only support the grading edition .
